language:
    csharp
sudo: required
mono: none 
dotnet: 3.1

os:
  - linux

before_script:
    - dotnet restore ".\challenges.csproj"
    
script:
    - dotnet build ".\challenges.csproj" -c Release
    - dotnet test "\challenges.csproj" -c Release -v n
